const phoneStates={
'PH-01':{name:'Today / Normal',meta:'Today',title:'保持今天的计划。',decision:'不需要做得更多。\n今天只需要保持稳定。',reason:'近期没有新的证据需要改变当前方向。短周期波动已被系统留在背景里。',action:'轻松走 20 分钟',primary:'开始',next:'W-01',flow:'GF-01',door:'为什么这样安排？',doorNext:'PH-08'},
'PH-02':{name:'Adjustment Needed',meta:'Today · Adjustment',title:'今天需要小幅调整。',decision:'降低强度，\n不是放弃计划。',reason:'当前证据支持临时减量，而不是永久改变方向。',action:'改为轻松恢复日',primary:'接受调整',next:'PH-05',door:'查看触发依据',doorNext:'PH-08'},
'PH-03':{name:'Guardrail',meta:'Guardrail',title:'先停止。',decision:'现在不需要猜原因。\n先保护身体。',reason:'本次信号不足以形成医学结论。若症状持续、加重或符合既定安全规则，进入 Clinical Route。',action:'停止当前活动',primary:'我已停止活动',next:'PH-10',flow:'GF-03',danger:true,door:'查看安全路径与 Authority',doorNext:'PH-10'},
'PH-04':{name:'Decision Needed',meta:'Decision Needed',title:'过去的经验正在改变今天。',decision:'这次不再重复\n上一次的默认选择。',reason:'已验证 Learning 被预加载到当前决策。系统只改变决策起点，不替你做最终决定。',action:'采用新的默认方案',primary:'确认本次决定',next:'PH-05',flow:'GF-04',door:'查看被复用的 Learning',doorNext:'PC-07'},
'PH-05':{name:'Current Program',meta:'Current Program',title:'当前计划',decision:'稳定优先。\n让计划能够被验证。',reason:'本周期只保留少数关键变量，避免同时改变太多条件。',action:'继续当前 14 天周期',primary:'查看下一行动',next:'PH-06',door:'查看计划依据',doorNext:'PH-08'},
'PH-06':{name:'Next Action Detail',meta:'Next Action',title:'下一行动',decision:'轻松走 20 分钟',reason:'目标是完成可验证行动，而不是追求单次表现。',action:'现在开始',primary:'发送到 Watch',next:'W-01',flow:'GF-01',door:'稍后完成',doorNext:'PH-07'},
'PH-07':{name:'Handoff Queue',meta:'Handoff',title:'待处理交接',decision:'有 2 个事项\n等待你的确认。',reason:'系统把低紧迫、需要人决定的事项留到自然检查点。',action:'查看下一项',primary:'处理',next:'PH-04',door:'暂时不处理',doorNext:'PH-01'},
'PH-08':{name:'Evidence Door',meta:'Evidence Door',title:'为什么这样安排？',decision:'先给结论。\n需要时，再展开复杂性。',reason:'当前建议来自行为一致性、恢复方向与既定安全边界；关键未知仍需要后续检查点确认。',action:'进入深度理解',primary:'在 PC 查看证据',next:'PC-01',flow:'GF-02',door:'回到 Today',doorNext:'PH-01'},
'PH-09':{name:'Data Health / Sync',meta:'Data Health',title:'数据状态',decision:'系统可以不完整，\n但不能假装完整。',reason:'最近同步正常；任何缺口都必须可见，不得被 AI 叙事覆盖。',metrics:[['Last sync','12 min ago'],['Coverage','Expected'],['Authority','Mac Canon']],action:'查看同步详情',primary:'刷新视图',next:'PH-09',door:'隐私与权限',doorNext:'PH-10'},
'PH-10':{name:'Me / Privacy / Authority',meta:'Me · Authority',title:'主权与边界',decision:'你的健康系统，\n必须先属于你。',reason:'用户主权、临床权威、数据边界与恢复能力都是正确性的一部分。',metrics:[['Health Canon','Local-first'],['Clinical authority','External'],['AI role','Evidence synthesis']],action:'查看 Authority Map',primary:'打开',next:'PC-08',door:'回到 Today',doorNext:'PH-01'}
};
const watchStates={'W-01':{name:'Now',big:'WALK',sub:'20 min',action:'START'},'W-02':{name:'Training',big:'12:48',sub:'112 bpm · easy',action:'END'},'W-03':{name:'Complete',big:'DONE',sub:'ACT receipt captured',action:'✓'},'W-04':{name:'Skip / Later',big:'LATER',sub:'No penalty',action:'OK'},'W-05':{name:'Discomfort / Guardrail',big:'DISCOMFORT',sub:'Stop activity',action:'STOP',danger:true},'W-06':{name:'Status',big:'READY',sub:'Synced · 4 min ago',action:'OK'}};
const pcStates={
'PC-01':{name:'Current Health Thesis',eyebrow:'CURRENT HEALTH THESIS',title:'改善正在发生。\n现在最重要的是确认它是否真实、稳定、值得继续。',lead:'支持证据来自行为一致性与恢复方向；仍有一个关键未知：下一临床检查点是否支持同一方向。',meta:[['CONFIDENCE','Moderate'],['NEXT CHECKPOINT','12 days'],['KEY UNKNOWN','Clinical confirmation']]},
'PC-02':{name:'Evidence Map',eyebrow:'EVIDENCE MAP',title:'把“为什么相信”\n放在判断下面。',lead:'Signal、Fact、Decision 分层呈现。证据强度、来源与未知必须可追溯。',evidence:true},
'PC-03':{name:'Health Pathways',eyebrow:'HEALTH PATHWAYS',title:'从证据到行动，\n每一步都能解释。',lead:'CTX → EVD → DEC → WPK → ACT → OUT → LRN。页面显示的是路径，不是黑箱建议。',pathway:true},
'PC-04':{name:'Active Experiment',eyebrow:'ACTIVE EXPERIMENT',title:'一次只改变\n足够少的变量。',lead:'把行为、结果与归因分开。Experiment 不是“打卡挑战”，而是可被判定的学习单元。',meta:[['WINDOW','14 days'],['PRIMARY ACT','Low-intensity walk'],['STOP RULE','Guardrail first']]},
'PC-05':{name:'Outcome Review',eyebrow:'OUTCOME REVIEW',title:'做了以后，\n到底发生了什么？',lead:'先核实行为是否发生，再看 Outcome。没有 verified ACT，就不能声称 Outcome 来自该行动。',evidence:true},
'PC-06':{name:'Learning Adjudication',eyebrow:'LEARNING ADJUDICATION',title:'不是每一个变化，\n都有资格成为 Learning。',lead:'只有证据足够、边界清楚、未越过临床权威时，才把观察沉淀为可复用经验。',meta:[['STATUS','Candidate'],['ATTRIBUTION','Limited'],['REUSE','Not yet']]},
'PC-07':{name:'Longitudinal Causal Memory',eyebrow:'LONGITUDINAL CAUSAL MEMORY',title:'真正的复利，\n发生在下一次决定之前。',lead:'Learning 只有在第二次任务中被预加载、被使用、并改变决策起点时，才开始成为健康资产。',pathway:true,reuse:true},
'PC-08':{name:'Clinical Collaboration',eyebrow:'CLINICAL COLLABORATION',title:'系统可以整理证据，\n但不能吞掉临床权威。',lead:'需要医学判断的事项必须明确移交。AI 可以准备问题、证据与时间线，但不能把 Signal 变成诊断。',authority:true}
};
const flows={'GF-01':{name:'Today → Watch Action',desc:'一个日常判断，被压缩成一件行动，并在身体边缘完成 verified ACT。',route:['PH-01','PH-06','W-01','W-02','W-03']},'GF-02':{name:'Evidence Door → PC Deep Dive',desc:'当用户主动问“为什么”，复杂性才从 iPhone 展开到 PC。',route:['PH-08','PC-01','PC-02','PC-03']},'GF-03':{name:'Discomfort → Guardrail / Authority',desc:'先停止，再交接；Watch 不诊断，iPhone 不越权，PC 为临床协作准备证据。',route:['W-05','PH-03','PH-10','PC-08']},'GF-04':{name:'Outcome → Learning → Reuse',desc:'Outcome 被审判为 Learning，并在下一任务开始前改变默认决策。',route:['PC-05','PC-06','PC-07','PH-04']}};
let currentPhone='PH-01',currentPC='PC-01',currentWatch='W-01',currentMode='phone';
function announce(msg){const l=document.getElementById('live');l.textContent='';requestAnimationFrame(()=>l.textContent=msg)}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('on');setTimeout(()=>t.classList.remove('on'),1700);announce(msg)}
function flash(){const f=document.getElementById('flash');f.classList.add('on');setTimeout(()=>f.classList.remove('on'),500)}
function setMode(mode,btn){currentMode=mode;document.querySelectorAll('.mode').forEach(x=>x.classList.remove('on'));document.getElementById('mode-'+mode).classList.add('on');document.querySelectorAll('.surfaceSwitch button').forEach(x=>x.classList.toggle('on',x.dataset.mode===mode));const names={phone:'iPhone · Navigate',watch:'Watch · Embody',pc:'PC · Deliberate',flows:'Gold Flows'};document.getElementById('crumb').textContent=names[mode];announce(names[mode])}
function navigate(surface,screenId){if(surface==='phone'){currentPhone=screenId;renderPhone();setMode('phone')}if(surface==='pc'){currentPC=screenId;renderPC();setMode('pc')}if(surface==='watch'){currentWatch=screenId;renderWatchMenu();showWatch(screenId);setMode('watch')}}
function handoff(flowId,destinationId){flash();toast(flowId+' · handoff');if(destinationId.startsWith('PH-'))navigate('phone',destinationId);else if(destinationId.startsWith('PC-'))navigate('pc',destinationId);else if(destinationId.startsWith('W-'))showWatch(destinationId)}
function renderPhone(){const s=phoneStates[currentPhone],screen=document.getElementById('phoneScreen');screen.className='phoneScreen'+(s.danger?' guardrailState':'');const metrics=s.metrics?`<div class="metricList">${s.metrics.map(x=>`<div class="metricLine"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div>`:'';screen.innerHTML=`<div class="phoneMeta">${currentPhone} · ${s.meta}</div><div class="phoneTitle">${s.title}</div><div class="phoneDecision">${s.decision.replaceAll('\n','<br>')}</div><div class="phoneReason">${s.reason}</div>${metrics}<div class="phoneAction"><div class="actionEyebrow">ONE NEXT MOVE</div><h3>${s.action}</h3><button class="primary" onclick="phonePrimary()">${s.primary}</button><div class="safety">${s.danger?'Safety before interpretation':'如有异常不适，停止活动。'}</div><div class="evidenceDoor" onclick="phoneDoor()">${s.door} →</div><div class="bottomNav"><span class="active">Today</span><span>Path</span><span>Evidence</span><span>Me</span></div></div>`;document.querySelectorAll('#phoneMenu .stateCard').forEach(x=>x.classList.toggle('on',x.dataset.id===currentPhone))}
function phonePrimary(){const s=phoneStates[currentPhone];if(!s.next)return;if(s.next.startsWith('W-')){handoff(s.flow||'GF-01',s.next);showWatch(s.next)}else if(s.next.startsWith('PC-'))handoff(s.flow||'GF-02',s.next);else navigate('phone',s.next)}
function phoneDoor(){const s=phoneStates[currentPhone];if(!s.doorNext)return;if(s.doorNext.startsWith('PC-'))handoff(s.flow||'GF-02',s.doorNext);else navigate('phone',s.doorNext)}
function showWatch(id){currentWatch=id;const s=watchStates[id],d=document.getElementById('watchDock');d.classList.add('on');document.getElementById('watchNow').textContent=id+' · '+s.name.toUpperCase();document.getElementById('watchBig').textContent=s.big;document.getElementById('watchSub').textContent=s.sub;const b=document.getElementById('watchAction');b.textContent=s.action;b.className='watchAction'+(s.danger?' danger':'')+(id==='W-03'?' watchDone':'');announce('Watch '+s.name)}
function watchPrimary(){if(currentWatch==='W-01'){showWatch('W-02');return}if(currentWatch==='W-02'){showWatch('W-03');toast('GF-01 · verified ACT receipt');return}if(currentWatch==='W-05'){document.getElementById('watchDock').classList.remove('on');handoff('GF-03','PH-03');return}document.getElementById('watchDock').classList.remove('on')}
function renderPhoneMenu(){document.getElementById('phoneMenu').innerHTML=Object.entries(phoneStates).map(([id,s])=>`<div class="stateCard" data-id="${id}" onclick="navigate('phone','${id}')"><small>${id}</small><strong>${s.name}</strong><p>${s.title}</p></div>`).join('')}
function renderWatchMenu(){document.getElementById('watchMenu').innerHTML=Object.entries(watchStates).map(([id,s])=>`<div class="flowCard" onclick="showWatch('${id}')"><div class="flowNo">${id}</div><h3>${s.name}</h3><p>${s.big} · ${s.sub}</p><div class="route"><span>2–5 sec target</span><span>${s.danger?'Guardrail':'Body Edge'}</span></div></div>`).join('')}
function renderPCNav(){document.getElementById('pcNav').innerHTML=Object.entries(pcStates).map(([id,s])=>`<button data-id="${id}" onclick="navigate('pc','${id}')">${s.name}</button>`).join('')}
function renderPC(){const s=pcStates[currentPC];let extra='';if(s.evidence)extra=`<div class="evidenceGrid"><div class="panel"><h4>STRONGER EVIDENCE</h4><div class="evidenceItem"><strong>Behavior consistency</strong><span>Verified across current synthetic window</span></div><div class="evidenceItem"><strong>Recovery direction</strong><span>Supports current thesis, not causal proof</span></div></div><div class="panel"><h4>UNKNOWN</h4><p>Clinical confirmation remains unresolved. The system keeps this uncertainty visible.</p></div></div>`;if(s.pathway)extra+=`<div class="pathway"><div class="node">EVD</div><div class="node">DEC</div><div class="node hot">ACT</div><div class="node hot">OUT</div><div class="node">LRN</div></div>`;if(s.reuse)extra+=`<div class="learningReceipt">LRN-014 was preloaded before DEC-031 → default decision changed → REUSED</div>`;if(s.authority)extra+=`<div class="authorityBox"><strong>Clinical Authority remains external.</strong><p>Prepare evidence, timeline, questions and handoff context. Do not diagnose, prescribe or reinterpret medical authority.</p></div>`;if(s.meta)extra+=`<div class="pcMetaGrid">${s.meta.map(x=>`<div><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('')}</div>`;document.getElementById('pcCanvas').innerHTML=`<div class="pcEyebrow">${currentPC} · ${s.eyebrow}</div><h2>${s.title.replaceAll('\n','<br>')}</h2><div class="pcLead">${s.lead}</div>${extra}`;document.querySelectorAll('#pcNav button').forEach(x=>x.classList.toggle('on',x.dataset.id===currentPC))}
function renderFlows(){document.getElementById('flowGrid').innerHTML=Object.entries(flows).map(([id,f])=>`<div class="flowCard" onclick="runFlow('${id}')"><div class="flowNo">${id}</div><h3>${f.name}</h3><p>${f.desc}</p><div class="route">${f.route.map(x=>`<span>${x}</span>`).join('')}</div></div>`).join('')}
async function runFlow(id){const f=flows[id];toast(id+' · '+f.name);for(const step of f.route){await new Promise(r=>setTimeout(r,520));if(step.startsWith('PH-'))navigate('phone',step);if(step.startsWith('PC-'))navigate('pc',step);if(step.startsWith('W-'))showWatch(step)}}
renderPhoneMenu();renderPhone();renderWatchMenu();renderPCNav();renderPC();renderFlows();